TECHNICAL IMPROVEMENT: Upgrade spree to 4.0
TerraCycleUS/spree_avatax_certified pull request #5
Opened 2019-12-09 12:33 UTC by robert-hromej

2019-12-09 14:35 UTC, robert-hromej commented
![](https://github.trello.services/images/mini-trello-icon.png) [Replace class_eval/module_eval for spree_avatax_certified](https://trello.com/c/LLXsb79k/1726-replace-classeval-moduleeval-for-spreeavataxcertified)

2019-12-10 09:52 UTC, viktordanch approved these changes

2019-12-10 10:33 UTC, balazslaszlo approved these changes

2019-12-10 13:03 UTC, rczjns requested changes

2019-12-10 13:03 UTC, rczjns commented on app/models/spree/address_decorator.rb
> +Spree::Address.prepend Spree::AddressDecorator
add a newline to the end, please

2019-12-10 13:03 UTC, rczjns commented on app/models/spree/adjustment_decorator.rb
> +    def self.prepended(base)
I'm thinking about is it possible to use `extend module` for a class to add a new class method for that?

e.g.
```
module XClassDecorator
  scope :not_tax, -> { where.not(source_type: 'Spree::TaxRate') }
end

X.extend XClassDecorator
```

I think it's more readable than `def self.prepended(base)`.
What do you think?

2019-12-10 13:03 UTC, rczjns commented on app/models/spree/order_decorator.rb
> +    def self.prepended(base)
same like above

2019-12-10 13:03 UTC, rczjns commented on app/models/spree/order_decorator.rb
> +Spree::Order.prepend Spree::OrderDecorator
new line please

2019-12-10 13:03 UTC, rczjns commented on app/models/spree/shipment_decorator.rb
> +  # ShipmentDecorator
I think it makes no sense to copy the name of the class/module as documentation...

2019-12-10 14:17 UTC, robert-hromej commented on app/models/spree/adjustment_decorator.rb
> +    def self.prepended(base)
@rczjns `extend module` - not work in this example.
```
$ irb
irb(main):001:0> class X
irb(main):002:1>   def self.scope(args)
irb(main):003:2>     puts "call scope method with args: '#{args}'"
irb(main):004:2>   end
irb(main):005:1> 
irb(main):006:1>   scope 'from X class'
irb(main):007:1> end
call scope method with args: 'from X class'
=> nil
irb(main):008:0> 
irb(main):009:0> p X.new.respond_to?(:instance_method_a)
false
=> false
irb(main):010:0> p X.respond_to?(:klass_method)
false
=> false
irb(main):011:0> module XClassDecorator
irb(main):012:1>   module ClassMethods
irb(main):013:2>     def klass_method(args)
irb(main):014:3>       # ...
irb(main):015:3>     end
irb(main):016:2>   end
irb(main):017:1> 
irb(main):018:1>   def self.prepended(base)
irb(main):019:2>     base.scope 'from XClassDecorator'
irb(main):020:2>     base.singleton_class.prepend(ClassMethods)
irb(main):021:2>   end
irb(main):022:1> 
irb(main):023:1>   def instance_method_a(args)
irb(main):024:2>     # ...
irb(main):025:2>   end
irb(main):026:1> end
=> :instance_method_a
irb(main):027:0> X.prepend XClassDecorator
call scope method with args: 'from XClassDecorator'
=> X
irb(main):028:0> p X.new.respond_to?(:instance_method_a)
true
=> true
irb(main):029:0> p X.respond_to?(:klass_method)
true
=> true
irb(main):030:0> 
```

I don't like this style(`prepended`, `ClassMethods`....) but only this work correctly

2019-12-10 14:17 UTC, robert-hromej commented on app/models/spree/adjustment_decorator.rb
> +    def self.prepended(base)
@rczjns I tried with extend module, but not working

2019-12-10 15:34 UTC, rczjns approved these changes

2019-12-11 09:42 UTC, robert-hromej commented
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate to Zeitwerk loader](https://trello.com/c/E8pZ2kZS/1723-migrate-to-zeitwerk-loader)

2019-12-12 13:44 UTC, padavanocskos approved these changes

2019-12-12 14:42 UTC, balazslaszlo approved these changes

2020-01-21 15:46 UTC, merged